[package]
name = "aicup2019"
version = "0.1.0"
edition = "2018"

[dependencies]
model = { path = "model", package = "aicup2019-model" }
trans = { path = "model/trans" }

[profile.release]
debug = true